#!/bin/bash
rm -rf build-verif
mkdir -p build-verif

if [ -z $VRASED_HW_MOD ]; then
    export VRASED_HW_MOD='hw-mod'
fi
echo "using HW-Mod at '../../vrased/$VRASED_HW_MOD'"

# Copy VRASED's Verilog source code to temp directory
cp ../../openmsp430/msp_core/openMSP430_undefines.v ./build-verif/
cp ../../openmsp430/msp_core/openMSP430_defines.v ./build-verif/
cp ../../openmsp430/msp_core/vrased-config.v ./build-verif/
cp ../../vrased/$VRASED_HW_MOD/*.v ./build-verif/

# Specification
cp ../../verification_specs/ltl_specs.smv ./build-verif
cp ../../verification_specs/vrased-config.smv ./build-verif

# Override default SMV spec if one exists in the hw-mod directory (i.e., hw-mod-auth)
cp ../../vrased/$VRASED_HW_MOD/ltl_specs.smv ./build-verif/

for filename in ./build-verif/*.v; do
	sed -i "s/always @(posedge clk)/always @(*)/g" $filename
done

cd verilog2smv-1.1.2/script/
./verilog2smv.sh ../../build-verif/vrased.v ../../build-verif/vrased_generated.smv vrased
cd -

sed -i "s/IVAR/VAR/g" ./build-verif/vrased_generated.smv # Hacky here since IVAR doesnt work properly
echo '#include "ltl_specs.smv"' >> ./build-verif/vrased_generated.smv

./NuSMV -pre cpp ./build-verif/vrased_generated.smv

rm -rf build-verif
